services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*

  ingest:
    volumes:
      - ./ingest:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=true
